addr: ":8080"
endpoints:
  first:
    topic: topic1
    producer: confluent
  second:
    topic: topic1
    producer: ibm
  another:
    first:
      topic: topic1
      producer: segment
producers:
  confluent:
    type: kafka
    metricsEnabled: true
    client-config:
      bootstrap.servers: broker:9092
      statistics.interval.ms: 5000
  ibm:
    type: sarama
    metricsEnabled: true
    metricsFlushDuration: 5s
    client-config:
      bootstrap.servers: broker:9092
  segment:
    type: segment
    metricsEnabled: true
    metricsFlushDuration: 5s
    client-config:
      bootstrap.servers: broker:9092
      batch.timeout: 10ms
metrics:
  enabled: true
