addr: ":8080"
endpoints:
  first:
    topic: topic1
    producer: confluent
  second:
    topic: topic1
    producer: ibm
  another:
    first:
      topic: topic1
      producer: segment
producers:
  confluent:
    type: kafka
    clientConfig:
      bootstrap.servers: broker:9092
      statistics.interval.ms: 5000
  ibm:
    type: sarama
    metricsFlushDuration: 5s
    clientConfig:
      bootstrap.servers: broker:9092
  segment:
    type: segment
    metricsFlushDuration: 5s
    clientConfig:
      bootstrap.servers: broker:9092
      batch.timeout: 10ms
metrics:
  enable:
    all: true
  otel:
    endpoint: otel-collector:4317
    tls:
      insecure: true
